### ISSUE TITLE
revealjs_css_files are not copied in _build/revealjs/_static

### ISSUE THREAD

**Issue by djangoliv** [attakei/sphinx-revealjs#120]
with the configuration

```
revealjs_css_files = [
    "revealjs4/plugin/highlight/zenburn.css",
    "custom.css",
]
```

The file `custom.css` is found but not copied in `_build/revealjs/_static`

So the `_build/revealjs/` directory is not independent since it contains absolute links like: `/home/user/my_proj/custom.css`.
And we can not copy the result to another computer for example.

Regards

**Comment by attakei** [comment]
If `zenburn.css` are copied by your code, `revealjs_css_files` are working rightly.

I think that there are problems from file-specifing in conf, and not issue for sphinx-revealjs,

**Comment by attakei** [comment]
At least, your `revealjs_css_files` are invalid syntax.
Please provide right values from `conf.py` and prefer to provide all `revealjs_XXX` attributes from `conf.py`

**Comment by djangoliv** [comment]
I fixed the syntax pb. 
All the conf is in the `conf.py` file and the `custom.css` file is nearby `conf.py`

```
$ ls my_proj
_build index.rst conf.py custom.css Makefile
$ make revealjs
$ find _build/ |grep custom.css 
>>
$ find _build/ |grep zenburn.css
>> _build/revealjs/_static/revealjs4/plugin/highlight/zenburn.css
```

If you have a `custom.css` file, what configuration to use so that it is correctly declared and copied into the `_build directory` ?

conf.py
```
...
# -- Options for ReajealJs ------------------------------------------------

revealjs_style_theme = "moon"
revealjs_script_conf = """
{
    transition: 'none',
}
"""
revealjs_script_plugins = [
    {
        "name": "RevealHighlight",
        "src": "revealjs4/plugin/highlight/highlight.js",
    },
]
revealjs_css_files = [
    "revealjs4/plugin/highlight/zenburn.css",
    "custom.css",
]
```

**Comment by attakei** [comment]
Please try to set `revealjs_static_path = ""`. you must specify explicitly where are directory of static files.

But, this settings consider all files are static contents.
I recommend to these usage:
- Create `_static` directory
- Move `custom.css` into `_static`

**Comment by djangoliv** [comment]
Thanks i missed revealjs_static_path
It works

Regards
