### ISSUE TITLE
Accept any `data-` attributes in behavior directive

### ISSUE THREAD

**Issue by attakei** [attakei/sphinx-revealjs#156]
## Description

`revealjs-section` and `revealjs-break` have options to handle behaviors. (List is [here](https://github.com/attakei/sphinx-revealjs/blob/master/sphinx_revealjs/directives.py#L30))

These are attributes for using by Reveal.js itself, but there are cases to need set custom attributes for using external plugins.

## To Do

- [x] Find a design that directives accepts any or `data-` options.
- [x] Implement if it can.

**Comment by attakei** [comment]
Release feature by v3.0.0

**Comment by achimwackerow** [comment]
Thanks for implementing that any data- option is accepted.
