### ISSUE TITLE
Nested Lists Aren't Rendered Correctly

### ISSUE THREAD

**Issue by ens-scmeeu** [attakei/sphinx-revealjs#161]
I am using version 2.9.3 with sphinx 7.2.6.

This example slide:

```rest
Indent Test
-----------

* This should not be indented
* This should not be indented either
   * This should be indented as child of the line above
```

is rendered as this HTML:

```html
<section>
  <h3>Indent Test</h3>
  <ul class="simple">
    <li>
      <p>This should not be indented</p>
    </li>
    <li>
      <dl class="simple">
        <dt>This should not be indented either</dt>
        <dd>
          <ul>
            <li>
              <p>This should be indented as child of the line above</p>
            </li>
          </ul>
        </dd>
      </dl>
    </li>
  </ul>
</section>
```

When rendered in the browser, the 2nd line doesn't show as a bullet at all and since it is missing the `<p>` tag, it is also not inheriting paragraph CSS styling. Most importantly, I don't think this 2nd line should be a part of the nested list, only the line beneath it, so it should be a plain `<li>` line the line above it. Due to this last part the 2nd line isn't rendering as a part of the list at all and isn't correctly aligned with the line above.

If this IS the desired rendering, then renderjs itself certainly doesn't like it, and with default CSS of the builtin themes certainly doesn't render it in any desirable way.

Rendering it this way, for example, results in the desired rendering in a browser:

```html
<section>
  <h3>Indent Test</h3>
  <ul class="simple">
    <li>
      <p>This should not be indented</p>
    </li>
    <li>
        <p>This should not be indented either</p>
          <ul>
            <li>
              <p>This should be indented as child of the line above</p>
            </li>
          </ul>
    </li>
  </ul>
</section>
```

**Comment by attakei** [comment]
This is for spec of reStructuredText, and not issue about sphinx-revealjs.

You should blank between parent and child if you want to write nested list.

```rst
Indent Test
-----------

* This should not be indented
* This should not be indented either

   * This should be indented as child of the line above
```

Please see [Sphinx docs](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#lists-and-quote-like-blocks).

**Comment by ens-scmeeu** [comment]
Ahh...nice. I'm admittedly new to reStructuredText. That renders better, but puts it in a `<blockquote>`. Anyway to have it not do that?

**Comment by attakei** [comment]
Prev my example is included unnecessary space. Try this.

```rst
Indent Test
-----------

* This should not be indented
* This should not be indented either

  * This should be indented as child of the line above
```

**Comment by ens-scmeeu** [comment]
Perfect, thanks so much for the help. Will close this out.
