### ISSUE TITLE
Improvements to CSS workflow

### ISSUE THREAD

**Issue by playpauseandstop** [attakei/sphinx-revealjs#27]
Hi! First of all, thanks for the amazing plugin to make `reveal.js` slides within the Sphinx. I am very happy to found it recently and already used for my [last slides](https://igordavydenko.com/slides/lvivpy-9.html).

In total it was very smooth experience, but I'd like to discuss some possible modifications to CSS workflow, while working with `sphinx-revealjs`.

## Custom CSS configuration

`revealjs_style_theme` allows to use custom reveal.js theme, basic (`black`, `white`, etc) or custom. In most cases, this might be enough. For my slides I copied default `white` theme and provide some updates (mostly for fonts).

While this is OK for one slides, it might be very time-consuming, if I'd like to change the default theme to use somewhen later.

With that in mind about to provide advanced ability to supply custom CSS rules via some extra `revealjs_custom_styles` config instead?

In that case configuration below allows user to easily switch between reveal.js themes, but do not lose any custom modifications,

```python
revealjs_style_theme = "white"
revealjs_custom_styles = """
.mt-5 {
  margin-top: 3rem !important;
}

.text-muted {
  color: grey !important;
}
"""
```

## Emtpy sections with background

I have a slide with backround,

```rst
notitle
-------

.. revealjs_section::
    :data-background-image: _static/lvivpy-9/github-actions.png
    :data-background-size: contain
```

In that slide I don't want to have `notitle` header rendered at all. As of now I'm able to do this by using CSS rule,

```css
section[data-background-image="_static/lvivpy-9/github-actions.png"] h3 {
  display: none;
}
```

But in reality I would like to have some "magic" way to do this without any extra CSS. I don't have an idea now, how it might look, but it widely common pattern to have slides only with background image, but without any text above it.

## Fonts improvements

`sphinx-revealjs` _allows_ to setup custom generic font, as well as include it from Google Fonts. However, I find those features a bit buggy.

1. `v1` of Google Fonts used, while it might be useful to migrate to latest `v2`
2. Custom generic font applied only to `body`, while in reality it should be applied to `.reveal` class instead
3. As headers and monospace fonts configured via `.reveal h1, .reveal h2, ...` & `.reveal pre, .reveal code` rules, it might be useful to allow setup `revealjs_header_font` & `revealjs_monospace_font` as well

With that in mind, I'd like to once again thank you on your work and if you'll be OK with some CSS improvements, I noted above, I would be glad to help with the implementation.

**Comment by attakei** [comment]
Thank you for using and feedback!

## > Custom CSS configuration

> With that in mind about to provide advanced ability to supply custom CSS rules via some extra revealjs_custom_styles config instead?

Yes, I plan adding confg for stylesheets to include other css files similar `html_css_files` .
If you want to customize style in current version, it mabye usefule `html_css_files` option as workaround (this option work revealjs builder).

> ## Emtpy sections with background

If you want `h3` level no-title section, please try to use `revealjs_break` directive.

example:

```rst
some section
------

.. revealjs_break::
   :notitle:
   :data-background-image: _static/lvivpy-9/github-actions.png
   :data-background-size: contain
```

**Comment by playpauseandstop** [comment]
@attakei 

Thanks for your comments.

Was not aware of `html_css_files`, will try to use it instead of overwriting reveal.js theme.

As well as will try to use your workaround for sections with empty header. _Maybe it is good idea to put this case to example slides?_

**Comment by attakei** [comment]
Tried write empty header section demo using `revealjs_break` that is like your presentation, and I think that it is worked well-done.

* Page: https://attakei.github.io/sphinx-revealjs/example-background-only-section.html
* Source: https://github.com/attakei/sphinx-revealjs/blob/master/demo/example-background-only-section.rst

In your case,  try replace like following:

(before)

```rst
notitle
-------

.. revealjs_section::
    :data-background-image: _static/lvivpy-9/github-actions.png
    :data-background-size: contain
```

(after)

```rst
.. revealjs_break::
    :notitle:
    :data-background-image: _static/lvivpy-9/github-actions.png
    :data-background-size: contain
```
 I read your reST source from https://igordavydenko.com/slides/_sources/lvivpy-9.rst.txt

**Comment by playpauseandstop** [comment]
Hi @attakei,

Yeah,

```rst
.. revealjs_break::
    :notitle:
    :data-background-image: _static/lvivpy-9/github-actions.png
    :data-background-size: contain
```

works as expected. Thanks a lot!

**Comment by playpauseandstop** [comment]
As I started to move my changes to reveal.js theme into separate CSS file, I also remembered another improvement I had in mind.

My slides use `tomorrow-night` highlight.js theme, while by default `zenburn` theme loaded. Maybe, it is reasonable to disable loading default highlight.js theme for reveal.js, when it is not expected to be used?

**Comment by attakei** [comment]
Yes, your thinking are right.

Template includes zenbun.css from first release , beacause I have used higithlght.js already any presentations with reveal.js.
`sphinx-revealjs` should have used any css explicitly (it would been better to use explicitly than using implicitly)

**Comment by attakei** [comment]
On current version(>= `0.12.0`), set only reveal.css as stylesheet file in `sphinx-revealjs`.

If you want other theme of highlight.js, insert into it `revealjs_css_files` (with managing file at your repo).
