### ISSUE TITLE
Supporting reveal.js 4.x

### ISSUE THREAD

**Issue by attakei** [attakei/sphinx-revealjs#31]

**Comment by ukos-git** [comment]
I tried to install with reveal.js 4.1

I cloned [revealjs](https://github.com/hakimel/reveal.js.git) to the sphinx project root and used the following custom config in `conf.py` but it did not produce valuable output:

```
revealjs_static_path = ['revealjs/dist']
revealjs_css_files = ['reveal.css']
revealjs_script_files = ['reveal.js']
revealjs_style_theme = 'theme/black.css'
```

Is current recommendation to clone the [3.9 stable branch](https://github.com/hakimel/reveal.js/tree/v3.9) of revealjs?

**Comment by attakei** [comment]
In currently version, implement for sorting css files is incorrect order.
If use this conf, this write `link` tag of **theme style** prior to `link` of **revealjs core css**, browser does not render correctly.

## Workaround.

Set theme css file path into `revealjs_css_files`.

```python
revealjs_static_path = ['revealjs/dist']
revealjs_css_files = ['reveal.css', 'theme/black.css']
revealjs_script_files = ['reveal.js']
```

**Comment by attakei** [comment]
> Is current recommendation to clone the 3.9 stable branch of revealjs?

Yes. I reccomend to use revealjs 3.9 yet.
reveal.js 4.x has changes  of behavior of using plugins from version 3.x .
`sphinx-revealjs` cannot support new writing syntax for using plugins, then it does not work plugins.

(I am development for this issues in [feature/reveakhs-multi](https://github.com/attakei/sphinx-revealjs/tree/feature/revealjs-multi) branch )

**Comment by attakei** [comment]
On current version (`1.0.1`) , use Reveal.js 4.x to build presentation.
  
  If you use version `0.x` and want to change `1.x`, please see [migration document](https://sphinx-revealjs.readthedocs.io/en/latest/migrations.html).
