### ISSUE TITLE
project directory, with workbook and slides

### ISSUE THREAD

**Issue by inktvis75** [attakei/sphinx-revealjs#32]
Hi,

Is it possible to have a directory structure like this:

source/conf.py
source/index.rst
source/labs/<rst files for workbook>
source/slides/<rst files for slides>

so if I execute make html & make latexpdf, it's using the labs directory,
and make revealjs, it's going to use the slides directory ?

**Comment by attakei** [comment]
Sphinx can split source directory and conf directory.
If you place slide resources on only `slides`, you can do it by editing Makefile.

```makefile
revealjs: Makefile
    @$(SPHINXBUILD) -M revealjs slides "$(BUILDDIR)" -c $(SOURCEDIR) $(SPHINXOPTS) $(O)
```
