### ISSUE TITLE
PlantUML or Outside Extension support

### ISSUE THREAD

**Issue by mruge** [attakei/sphinx-revealjs#33]
I love the extension, but it seems to have issues with using other extensions...specifically i am attempting to use Plantuml.  That extension should render the uml blocks as a PNG before the build takes place, however the HTML5 builder used by RevealJS doesn't seem to permit that.

Not sure where to look about helping add that support.

```rest
Test Document
=============

Overview
--------

.. uml::

  Alice -> Bob
```

```
Exception occurred:
  File "/home/mruge/.local/lib/python3.8/site-packages/sphinx/writers/html5.py", line 793, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: plantuml
```

**Comment by attakei** [comment]
In this case, I edit sometimes `conf.py` to override behavior of custom nodes.

For `sphinxcontrib.plantuml`, edit your `conf.py` of document.

```python
def setup(app):
    from sphinxcontrib.plantuml import plantuml, _NODE_VISITORS
    _NODE_VISITORS["revealjs"] = _NODE_VISITORS["html"]
    app.add_node(plantuml, **_NODE_VISITORS)
```

I dont think that it is best approach, but It work as work-around.

**Comment by mruge** [comment]
That worked like a charm.  Thanks!

My workaround was to run 	plantuml _puml/*.puml -o ../_static/  which has some advantages with importing, etc.

But for small diagrams, doing them inline with   `.. uml::` is really nice.

Adding that block to `conf.py` worked great!

**Comment by attakei** [comment]
I plan that `sphinx-revealjs` catch external nodes behavior and override behavior in hook at future
