### ISSUE TITLE
Cannot overwrite properties defined in theme css with specifed `revealjs_css_files`

### ISSUE THREAD

**Issue by ftnext** [attakei/sphinx-revealjs#40]
## Environment

macOS
Python 3.8.6

- sphinx-revealjs 1.0.0

## Procedure

All files are here: https://github.com/ftnext/2021_slides/tree/e814031bd7d0178520250a84bc0cb4784830578e/source

### conf.py

```python
revealjs_static_path = ["_static"]

revealjs_css_files = [
    "revealjs4/plugin/highlight/zenburn.css",
    "css/common.css",
]
```

### _static/css/common.css

```css
.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
  text-transform: none;
}
```

I want to overwrite `text-transform` property set as `uppercase` by theme css (black.css).
I want to set `none` with `_static/css/common.css`.

## As is

Cannot overwrite the text-transform property.
The letters in headers are uppercase.

The HTML head tag:

```html
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="../_static/basic.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="../_static/revealjs4/dist/reveal.css" />
    <link rel="stylesheet" type="text/css" href="../_static/revealjs4/plugin/highlight/zenburn.css" />
    <link rel="stylesheet" type="text/css" href="../_static/css/common.css" />
    <link rel="stylesheet" href="../_static/revealjs4/dist/theme/black.css" type="text/css" />
```

## Expected

Enable to overwrite the text-transform property with custom css file (` _static/css/common.css`).

## In my opinion

I think it is the problem about the order of link tags.

Workaround is:

```html
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="../_static/basic.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="../_static/revealjs4/dist/reveal.css" />
    <!-- come theme css before custom css -->
    <link rel="stylesheet" href="../_static/revealjs4/dist/theme/black.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="../_static/revealjs4/plugin/highlight/zenburn.css" />
    <link rel="stylesheet" type="text/css" href="../_static/css/common.css" />
```

I will create a pull request to fix the order of the link tags.

**Comment by attakei** [comment]
I think that your opinion is right. Theme css file should be between core style and other custom css files.

Thanks for PR. Please wait until I confirm it.
