### ISSUE TITLE
Add `revealjs-noout` directive

### ISSUE THREAD

**Issue by attakei** [attakei/sphinx-revealjs#82]
## Spec

This is wrapper directive for other content that you do not want to display as presentation.
`revealjs` builder does not write contents In this directive to output file, but `html` builder writes it.

## Example

```rst
.. revealjs-noout::

   This content is not shown in presentation by revealjs.
```

```rst
.. revealjs-noout::

   Nested header
   =============

   Accept rst content
```

## Motivation

I want to head for that it outputs multiple contents appositely format by single source.

**Comment by jonahbeckford** [comment]
I use the following to conditionally select content:

```rst
.. only:: not dirrevealjs and not revealjs

  Indices and tables
  ==================

  * :ref:`genindex`
  * :ref:`modindex`
  * :ref:`search`
```

You could flip the logic (`dirrevealjs or revealjs`) as well.

**Comment by attakei** [comment]
I didn't know `only` directive!
On using it, I need not implement extra directives, and I make sense too.

Thanks for information.
