### ISSUE TITLE
Adding Grid Layouts Drag-and-Drop

### ISSUE THREAD

**Issue by tkoyama010** [attakei/sphinx-revealjs#86]
GitPitch have a `Grid Layouts Drag-and-Drop` feature. Can we add this to sphinx-revealjs?
https://gitpitch.github.io/gitpitch/#/grid-layouts/drag-and-drop?id=grid-layouts-drag-and-drop
![gitpitch-grid-layouts-positioning](https://user-images.githubusercontent.com/7513610/139577877-85060977-e362-470e-9da6-f45eb2487cef.png)

**Comment by attakei** [comment]
I am implementation experimentally by other packages ([sphinx-revealjs-float](https://github.com/attakei-lab/sphinx-revealjs-float)).
Please try this if it fits for your usecase or not.

[Build HTML is here](https://attakei-lab.github.io/sphinx-revealjs-float/)

**Comment by tkoyama010** [comment]
Thanks this is absolutely what I wanted. @attakei ++100
