### ISSUE TITLE
Resize problems ?

### ISSUE THREAD

**Issue by torerams** [attakei/sphinx-revealjs#94]
I just started using sphinx-revealjs that looks like a great framework, but I can not get the slides resize correctly.
Even the example has content out of the screen:

![Screenshot from 2022-01-10 21-13-08](https://user-images.githubusercontent.com/2785477/148833195-a4d9a2c9-f02a-4738-b904-1c7aa6b580a0.png)

Is there a way to get the content automatic fit the slide, or a manual way to resize slide or font ?

**Comment by attakei** [comment]
I do not know way to resize font automatic.

When you want to resize fonts of contents, please use additional CSS and container directive.

Example:

```rst
.. index.rst (wrap cotainer directive to render DIV element)
.. container:: wrapper

   .. code-block:: python

      def hello():
          return "world"
```

```css
/* cusotm.css (resize font in wrapper class) */
.reveal .wrapper {
  font-size: 0.5em;
}
```

```python
# conf.py ( use custom.css)
revealjs_css_files = [
    "custom.css",
]
```

I tried to fix demo at [this commit](https://github.com/attakei/sphinx-revealjs/commit/6377431c480d407968b87e811acfe68c502b8dee).

**Comment by torerams** [comment]
Thanks for the example code.
This solved my problem.
